modLoader="javafml"
loaderVersion="[36,)"
license="Custom license"

[[mods]]
modId="theabyss"
version="2.0.1-b1"
displayName="TheAbyss"
credits="Mod by Y3Z0N"
displayURL="https://www.curseforge.com/members/y4z0n/followers"
logoFile="logo.png"
authors="Y3Z0N"
description='''
The Abyss adds a brand new dimension to explore full of unique adventures and dangers! It's a dimension of darkness the only light comes from magical blocks and the various flora, fungi, and fauna of the dimension.
'''

[[dependencies.theabyss]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




